export enum UserValidationErrors {
    ERROR_CODE_NOT_REGISTERED = "001",
    ERROR_CODE_NOT_APPROVED = "002",
    ERROR_CODE_AUTHORIZED_FROM = "003",
    ERROR_CODE_NOT_APPROVED_EN = "004",
    ERROR_CODE_AUTH_REVOKED = "005",
    ERROR_CODE_AUTH_REVOKED_EN = "006",
}
