export const environment = {
  appname: "Shunting",
  production: false,
  mock: false,
  appVersion: "0.0.1",
  configUrl: "/assets/config",
  endpoints: {
    operations: {
      impianti: (id?: number) => 'operations/' + (id ? `impianti/${id}` : 'impianti'),
      impiantiPIC: (codicePIC: number) => 'operations/impianti/' + `codicePIC/${codicePIC}`,
      impiantiLista: 'operations/impianti/lista',
      impiantiAggiorna: 'operations/impianti/aggiorna',
      societa: "operations/societa",
      ruoli: (id?: number) => 'operations/' + (id ? `ruoli/${id}` : 'ruoli'),
      ruoliUtente: `operations/ruoli/utente`,
      squadramanovre: (id?: number) => 'operations/' + (id ? `squadramanovre/${id}` : 'squadramanovre'),
      squadramanovreAssociate: (idManovra: number) => `operations/squadramanovre/${idManovra}`,
      squadramanovreAssociazione: 'operations/squadramanovre/associazione',
      creaSquadramanovreAssociazione: 'operations/squadramanovre/associazione',
      aggiornaSquadramanovreAssociazione: 'operations/squadramanovre/associazione',
      deleteSquadramanovreAssociazione: (id: number) => `operations/squadramanovre/associazione/${id}`,
      statomanovre: (id?: number) => 'operations/' + (id ? `statomanovre/${id}` : 'statomanovre'),
      area: (id?: number) => 'operations/' + (id ? `area/${id}` : 'area'),
      areaByImpianto: (codiceImpianto: string) => `operations/area/impianto/${codiceImpianto}`,
      fascio: (id?: number) => 'operations/' + (id ? `fascio/${id}` : 'fascio'),
      fascioByCodiceAreaImp: (codiceAreaImp: string) => `operations/fascio/areaimp/${codiceAreaImp}`,
      binario: (id?: number) => 'operations/' + (id ? `binario/${id}` : 'binario'),
      creaBinario: () => 'operations/binario',
      modificaBinario: `operations/binario`,
      binarioLista: 'operations/binario/lista',
      binarioListaMinimale: 'operations/binario/lista-minimale',
      binarioByFascio: (idFascio: number) => `operations/binario/fascio/${idFascio}`,
      binarioByArea: (idArea: number) => `operations/binario/area/${idArea}`,
      tipologiemanovre: (id?: number) => 'operations/' + (id ? `tipologiemanovre/${id}` : 'tipologiemanovre'),
      operazioniaccessorie: (id?: number) => 'operations/' + (id ? `operazioniaccessorie/${id}` : 'operazioniaccessorie'),
    },
    manovre: {
      manovre: (id?: number) => 'movimentazioni/manovra/' + (id ? `dettaglio/${id}` : 'ricercamanovre'),
      manovra: (id?: number) => 'movimentazioni/' + (id ? `manovra/${id}` : 'manovra'),

      creaManovra: () => 'movimentazioni/manovra',
      ricercaManovre: () => 'movimentazioni/manovra/ricercamanovre',
      updateManovra: () => 'movimentazioni/manovra',
      deleteManovra: (idManovra: number) => `movimentazioni/manovra/${idManovra}`,
      accettarifiuta: 'movimentazioni/manovra/accettarifiuta',
      downloadM53: 'movimentazioni/manovra/download/m53',
      uploadManovre: 'movimentazioni/manovra/uploadmanovre',
      carriTemplate: 'movimentazioni/manovra/download/carri',
      uploadcarri: (idManovra: number) => `movimentazioni/manovra/uploadcarri/${idManovra}`,
      distintaCarri: (idManovra: number) => `movimentazioni/manovra/distintacarri/${idManovra}`,
      rimuoviCarri: (idManovra: number) => `movimentazioni/manovra/rimuovicarri/${idManovra}`,
      carriDefinitivi: (idManovra: number) => `movimentazioni/manovra/carridefinitivi/${idManovra}`,
      inizioFine: 'movimentazioni/manovra/iniziofine',
      dettaglioMad: (idManovra: number) => `movimentazioni/manovra/dettagliomad/${idManovra}`,
      sottomissioneMad: 'movimentazioni/manovra/sottomissionemad',
      accettazioneMad: 'movimentazioni/manovra/accettazionemad',
      dettaglioCdm: (idManovra: number) => `movimentazioni/manovra/dettagliocdm/${idManovra}`,
      sottomissioneCdm: 'movimentazioni/manovra/sottomissionecdm',
      accettazioneCdm: 'movimentazioni/manovra/accettazionecdm',
      allegato6a: (idManovra: number) => `movimentazioni/manovra/allegato6a/${idManovra}`,
      allegato6b: (idManovra: number) => `movimentazioni/manovra/allegato6b/${idManovra}`,
    },
    inquiry: {
      manovre: 'operations/inquiry/manovre',
      exportResults: 'operations/inquiry/exportmanovre',
      exportReport: 'operations/inquiry/exportrendicontazione'
    },
    utenti: "operations/utenti",
    validate: "operations/utenti/validate",
    createToken: "operations/auth/createtoken"
  }

};
